# Utiliza una imagen base de PHP con Apache
FROM php:7.4-apache

# Copia el contenido de tu proyecto PHP al directorio de trabajo del contenedor (/var/www/html)
COPY . /var/www/html

# Exponer el puerto 80 para el servidor Apache
EXPOSE 80

